language: clojure
script: lein doo node "tests" once
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
  email: false
env:
  global:
  - secure: ZSQEUG8tW3ismZ+cJ7XIDfgGPo8y8JcQiov2LPN2KziemmLeqg3MfCOY/I1SyOeH22610967uznwVot9WZ7HBywiHo1OKlKnsAf8BOBtvCO+T/5NhgGuZ5hDXkG0+pZBlzdyZcXVOLx8am3mr35XKruXBBVXbepdQku2kYaqx+8mVpSYwAmzOwoNnqX5wqpIXTnLuLtfR76wYcAUcX34eX4XqtbFe3xx4thsKsOzMFijkxTQAxqoiQN3w+FtBKIdKfyx2QbzscfYGDFo0yePPqe64rszLDWK34Th9AalK40JWr6SBxE2xtDFhyII9DOjgWV6mTvkEICjvuFaQapZxF9Nu7874ynlrRz4Ig7jr4XOGhtqbiPvr4+pSTY71qzLOpkG/pvHRxBnCcmoA8AfGOW7K5oJgsmNgXtpEyWZzCt//58a2LSeGA4zjnk+BuQvjNeixGlv+KD01SzTTyWTGwjOD9W036X954YGpLluHcemUbXXmnG2MFza87AJ88WHdlh41dlWgdTCQsyotzHKYMAI5JrRUe2MzXR0o5AJoVacYzM6m28Oo+t6xc2JK7OWMsUq6AAHQjcZkr+xBfnWs4STjdtFzjhgrQJUJldWmjWn3r1lcw7IaLOgrK15yxla4PsgaEyuG5cC+ySXkmjb+iPV/9eqAE8uzQjJ73ELyDU=
  - secure: Nruu2+tHZLI0/3CTpF+tJQigbAW6aV3MLSo7UkYK32dJ7KoR/sXRQ5ohpwlOsquA3DRmX6lZ44qzDeFMQEgQKbQE8LT4dif+2jnEsCHgaMrdOAYyAEu2JcpzF+O7iICtCXaaPR10AaJO9PuFOqavIzW8RyY3YHupHOFUkAjjP/mK6YcrKpq/0RSVF/fzEkLbvWcGcKWYtYeBS6NiIVUeuS9jz3xcESspGNu0pbfNpQqoPPzk6du477EZ2BjGkmPBE3JAZVwLaIdWO4Prp85v+6IM+4mBnhOPIho71qv1l4XWd/IfJhCI+3YUm7tB1kbn+0ot1jA81Nn31Gr0wT6FDnJFGtd7KuPUZlPgDfPmwD+7wVYeCXjuSpKjIhW8LrgtqXvvrKG+gxuHbwnXPd4lkfqyr/oUnLaABziSESZilf/nsW0Nk5JumRzvnAcbVGioH7I+Q4PrwlPFURh9Q9SnkA6ZohJOB2X2cj6jWu3rz696ctyULGj4v/mBrk0t6PpV8SIyHEOyFfPspI948PRtlfsX3V/LPhW/ZbU88MUrQYdgiY6EIKQ15yKfKAbXdcuhl78yUGxXpBlt+3Fiqo8+VrZMmxB+sma6QyuIyLZ+bb7P+ew1khrMOcW52NW+rARcFdh9g38YVtbRY8rSfDl0gINpY/ly4PtC1GMZxufDXus=
deploy:
- provider: script
  skip_cleanup: true
  script: lein release :patch
  on:
    branch: master
